/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab1;

public class App {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        App lib = new App();
        if(lib.someLibraryMethod()){
            System.out.println("Hello world");
        }
    }
}
